format = 1

[package]
provenance = "built-in"
id = "org.mochios.terra"
name = "Terra"
version = "0.1.0"
revision = 1
vendor = "mochiOS"
kind = "application"
architecture = "x86_64"
abi = "mochios-1"

[application]
entry = "entry.elf"
description = "Browse the web"
icon = "appicon.png"
resources = ["appicon.png"]

[[binary]]
path = "/system/applications/Terra.app/entry.elf"
kind = "application"
requires = [
    "ipc.client",
    "ipc.server",
    "window.create",
]
